services:
  - type: web
    name: frenos-coronel-diaz-erp-preview
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: frenos-coronel-diaz-postgres
          property: connectionString

databases:
  - name: frenos-coronel-diaz-postgres
    plan: free
